[project]
name = "DLC-Clarity-Smart-Contract-Redstone"

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[contracts.discreet-log-storage-v5-1]
path = "contracts/discreet-log-storage-v5-1.clar"
depends_on = []
