[project]
name = "DLC-Clarity-Smart-Contract-Redstone"

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[contracts.dlc-manager-pricefeed-v1-01]
path = "contracts/dlc-manager-pricefeed.clar"
depends_on = []

# [contracts.redstone-verify]
# path = "contracts/external/redstone-verify.clar"
# depends_on = []
